baseURL: "https://www.tynetime.com"
languageCode: "en-GB"
theme: "tyne-time-theme"
# Ensure new permalink structure for future posts
permalinks:
  posts: /:year/:month/:title/
# metadata
metaDataFormat: "yaml"
# taxonomies
taxonomies:
  category: "categories"
# Social
social:
  Twitter: "TyneTime"
  Facebook: "TyneTime"
  TwitterCreator: "KevinDoocey"
# Custom params for seo & snippets
params:
  homepageTitle: "Tyne Time — Newcastle United blog with news and opinion on matters at St. James' Park"
  subpageTitle: "Tyne Time"
  SiteName: "Tyne Time"
  Author:
    - name: "Kevin Doocey"
    - twitter: "@KevinDoocey"
  Twitter: "@TyneTime"

# General settings
pluralizeListTitles: false
canonifyURLs: true
